"""
Generates docs/Parking_Chatbot_Stage3.pptx — a presentation explaining the
parking chatbot and its administrator-approved MCP reservation storage.
Insert your own screenshots into the placeholder slides after generating it.

Usage:
    pip install -r docs/requirements-docs.txt
    python -m docs.generate_presentation
"""
from pptx import Presentation
from pptx.util import Inches, Pt

OUTPUT_PATH = "docs/Parking_Chatbot_Stage3.pptx"


def _add_title_slide(prs, title, subtitle):
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = subtitle


def _add_bullet_slide(prs, title, bullets):
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = title
    body = slide.placeholders[1].text_frame
    body.clear()
    for i, bullet in enumerate(bullets):
        p = body.paragraphs[0] if i == 0 else body.add_paragraph()
        p.text = bullet
        p.font.size = Pt(18)


def _add_screenshot_placeholder_slide(prs, title, note):
    slide = prs.slides.add_slide(prs.slide_layouts[5])
    slide.shapes.title.text = title
    box = slide.shapes.add_textbox(Inches(1), Inches(1.5), Inches(8), Inches(4))
    box.text_frame.text = f"[Insert screenshot here]\n\n{note}"


def build():
    prs = Presentation()

    _add_title_slide(prs, "Parking Reservation Chatbot — Stage 3",
                      "Admin approval, MCP reservation recording, and secure file storage")

    _add_bullet_slide(prs, "Problem & Scope", [
        "Chatbot answers parking questions: info, hours, prices, availability, location",
        "Collects reservation details conversationally: name, surname, car number, period",
        "Must not leak sensitive data",
        "Performance must be measured (latency, retrieval accuracy)",
    ])

    _add_bullet_slide(prs, "Architecture Overview", [
        "PDFs -> PyPDFLoader -> merged full-document text",
        "SemanticChunker: meaning-based chunking (embedding distance between sentences)",
        "Chunks + document metadata persisted in SQLite (source of truth)",
        "Chunks embedded into vector DB (Milvus, auto-fallback to Chroma)",
        "Dynamic data (hours/prices/availability) served from a separate SQL table",
    ])

    _add_bullet_slide(prs, "RAG & Conversation Flow", [
        "Intent classifier routes each message: static_info / dynamic_info / reservation / other",
        "static_info -> vector similarity search -> grounded LLM answer",
        "dynamic_info -> SQL lookup -> grounded LLM answer",
        "reservation -> slot-filling agent collects name, surname, car number, period",
    ])

    _add_bullet_slide(prs, "Stage 3: Approval-to-Storage Workflow", [
        "Chatbot escalates a completed reservation to the SQLite-backed admin request store",
        "Administrator reviews pending requests and approves or refuses through CLI or REST API",
        "Approval invokes ReservationRecorder; refusals are not written to confirmed storage",
        "Recorder can use in-process writing, FastAPI over HTTP, or the MCP stdio server",
        "Approved records append to a server-configured text file",
        "Record format: Name | Car Number | Reservation Period | Approval Time",
    ])

    _add_bullet_slide(prs, "MCP Storage: Security & Reliability", [
        "Output path is server-configured; clients cannot choose arbitrary file destinations",
        "Writer rejects empty, oversized, pipe, and newline-containing fields",
        "FastAPI endpoint supports an API key and per-client rate limiting",
        "Configure MCP_API_KEY and ADMIN_API_KEY before exposing APIs beyond a trusted network",
        "File locking prevents concurrent writes from interleaving; fsync flushes records to disk",
    ])

    _add_bullet_slide(prs, "Guardrails (PII Protection)", [
        "Presidio-based PII detection/redaction (falls back to regex if unavailable)",
        "Inbound: blocks credit card / SSN / IBAN pasted outside the reservation flow",
        "Outbound: redacts any PII that leaks into RAG-generated answers",
        "Reservation summary (user's own data) is exempt from outbound redaction by design",
    ])

    _add_bullet_slide(prs, "Evaluation Methodology", [
        "Test questions auto-generated by an LLM directly from ingested PDF chunks",
        "Each question has a ground-truth chunk id and reference answer",
        "Retrieval: Recall@K and Precision@K against ground-truth chunk ids",
        "Answer correctness: LLM-as-judge (or embedding similarity) vs reference answer",
        "Latency: retrieval and end-to-end timing, reported as mean/P50/P95",
    ])

    _add_screenshot_placeholder_slide(prs, "Demo — Answering a Static Info Question",
        "Chat screenshot: 'Where is the airport parking located?' and the bot's grounded answer.")
    _add_screenshot_placeholder_slide(prs, "Demo — Reservation Flow",
        "Chat screenshot: bot collecting name, surname, car number, and reservation period.")
    _add_screenshot_placeholder_slide(prs, "Demo — Admin Approval",
        "Admin CLI or REST API screenshot showing a pending request being approved.")
    _add_screenshot_placeholder_slide(prs, "Demo — Confirmed Reservation File",
        "Screenshot of data/reservations/confirmed_reservations.txt with the approved record.")
    _add_screenshot_placeholder_slide(prs, "Demo — Guardrail Blocking Sensitive Input",
        "Screenshot: bot refusing a message with a pasted credit card number.")
    _add_screenshot_placeholder_slide(prs, "Evaluation Report",
        "Screenshot of evaluation/REPORT.md: Recall@K, Precision@K, accuracy, latency.")

    _add_bullet_slide(prs, "Testing & CI/CD", [
        "Offline pytest coverage includes chatbot, admin approval, MCP writer, and API behavior",
        "GitHub Actions CI: lint + test + docker build on every push/PR",
        "Terraform (kreuzwerker/docker provider) to provision Milvus + app as code",
    ])

    _add_bullet_slide(prs, "Stage 3 Outcome", [
        "Reservation details flow from chatbot collection to administrator review",
        "Only approved reservations are recorded, with the approval time",
        "MCP-compatible and FastAPI writer options share the same validated storage logic",
        "Records are persisted in a durable, append-only text file",
        "Future work: LangGraph orchestration and broader load/integration testing",
    ])

    prs.save(OUTPUT_PATH)
    print(f"Saved presentation to {OUTPUT_PATH}")


if __name__ == "__main__":
    build()